### ISSUE TITLE
Upgrade to Core 3 preview

### ISSUE THREAD

**Issue by VR-Architect** [mmacneil/AspNetCoreApiStarter#4]
FYI, I tried to upgrade to the recent Core 3.x preview and couldn't get past this error which I logged at

https://github.com/JeremySkinner/FluentValidation/issues/975

**Comment by VR-Architect** [comment]
FYI to others testing this out with 3.x preview, I commented out and changed this line in Startup.cs
`//services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1).AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());

services.AddMvc();`

and I commented out the 3 files in the  /Models/Validation folder for now.  Then removed the reference to the FluentValidation NuGet package. Rebuild and ran. 

FYI, I was able to get this project to run with the 3.x preview running on new Visual Studio 2019 preview and C# 8.0 code. All Nuget packages were upgraded to latest previews. Works great!

**Comment by HEBOS** [comment]
Is this ever going to be fixed?
The current .NET Core is Preview 4,  and this is not fixed yet.
Can we even rely on this to be fixed, or give up if we plan to use .NET Core 3.0?

**Comment by HEBOS** [comment]
Is this ever going to be fixed?
The current .NET Core is Preview 4, and this is not fixed yet.
Can we even rely on this to be fixed, or give up if we plan to use .NET Core 3.0?

**Comment by mmacneil** [comment]
Sorry, I haven't the time currently to look at this - have you working the issues yourself and apply the steps @VR-Architect used to get it working?

**Comment by HEBOS** [comment]
@VR-Architect used the steps to disable fluent validation.
Nevertheless, it has been fixed (https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationObjectModelValidator.cs - see newly added method GetValidationVisitor). However, they haven't released it yet, as they wait for .NET Core 3.0 to be more mature.
Thanks anyway
