### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by stealthAngel** [mmacneil/AspNetCoreApiStarter#7]
As the title says. Some unit tests aren't working anymore :(

**Comment by mmacneil** [comment]
What error(s) are you getting and what test runner are you using?

**Comment by modiract** [comment]
I will make some print screens when I'm home. I pulled it on my work laptop ran unit tests and it works. I think it has to do with the visual studio version.

**Comment by stealthAngel** [comment]
https://gyazo.com/721a244808649068c075c0f1a620f561

this is what I'm getting.

**Comment by stealthAngel** [comment]
Seems like updating visual studio got  this fixed, thank you though :)
