### ISSUE TITLE
Issue in .Net Core 3

### ISSUE THREAD

**Issue by WaqarSarfaraz** [mmacneil/AspNetCoreApiStarter#9]
I just changed project framework on 3.0 & every time it throws an error 

`  Message=Method 'GetValidationVisitor' in type 'FluentValidation.AspNetCore.FluentValidationObjectModelValidator' from assembly 'FluentValidation.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0' does not have an implementation.`
  
This error throws on Wep api Startp.cs file in ConfigureServices method at line 134 which is 
`services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_3_0).AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());`
I have also Changed the Compatibility version to 3.0 but same Error

**Comment by mmacneil** [comment]
Hi, did you try upgrading the `FluentValidation` package?

**Comment by WaqarSarfaraz** [comment]
Thanks it's worked....
